FROM centos:latest
MAINTAINER SaDev Four <lokikiller@126.com>

#setup pymongo
RUN yum install -y git && mkdir -p /home/tools && cd /home/tools && \
    git clone git://github.com/mongodb/mongo-python-driver.git pymongo && \
    cd pymongo && python setup.py install && yum remove -y git

#copy source code
COPY ./code/data /home/code

#setup env
ENV MONGO_HOST 0.0.0.0
ENV MONGO_PORT 27017

#setup port
EXPOSE 27100

#setup run cmd
COPY ./misc/run.sh /home/run/
RUN chmod u+x /home/run/run.sh
CMD ["/bin/bash", "/home/run/run.sh"]
